services:
  django-web-app:
    build: .
    entrypoint: ["./django-web-app-entrypoint.sh"]
    ports:
      - "8000:8000"
    environment:
      - EMAIL_HOST=mailhog
      - EMAIL_PORT=1025
    networks:
      - mynetwork
    restart: unless-stopped
    volumes:
      - .:/uni_hub
    depends_on:
      - db

  frontend:
    build: ./frontend
    ports:
      - "5174:5173"
    networks:
      - mynetwork
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - django-web-app

  mailhog:
    image: mailhog/mailhog
    ports:
    - "8025:8025"
    networks:
    - mynetwork

  db:
    image: mysql:9.2.0
    ports:
      - "3006:3306"
    networks:
      - mynetwork
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: uni_hub_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - my-sql-data:/var/lib/mysql
volumes:
  my-sql-data:

networks:
  mynetwork:
    driver: bridge
