"""
Django settings for uni_hub project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^h=t%(zd5wlg65k!l%x^c#n_-m1qt9a_rs5zfz$b-c5jkivh1y"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "app",
    #External
    'corsheaders',
    'rest_framework',
    'djoser',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'storages',
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]


CORS_ALLOW_ALL_ORIGINS = True

# Allow sending credentials (cookies)
CORS_ALLOW_CREDENTIALS = True  

# Trusted domains (front-end)
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5174",  
]

ROOT_URLCONF = "uni_hub.urls"

AUTH_USER_MODEL = 'app.User'

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',  
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PAGINATION_CLASS': None,  # Explicitly disable pagination
    'PAGE_SIZE': None,
}


from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30), # Time before access token expires
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7), # Time before refresh token expires
    "ROTATE_REFRESH_TOKENS": True,
    "BLACKLIST_AFTER_ROTATION": True,
    "AUTH_HEADER_TYPES": ("Bearer",),
    "AUTH_COOKIE": "access_token", # HttpOnly cookie for security (can only be edited server side)
    "AUTH_COOKIE_SECURE": False, # True in production environment for HTTPS
    "AUTH_COOKIE_HTTP_ONLY": True,
    "AUTH_COOKIE_PATH": "/",
    "AUTH_COOKIE_SAMESITE": "Lax",
    "TOKEN_OBTAIN_SERIALIZER": "app.serializers.CustomTokenObtainPairSerializer",
}

DJOSER = {
    "USER_ID_FIELD": "email", # Set email to the main field instead of username
    "LOGIN_FIELD": "email", # Set email to the main field for logging-in instead of username
    "PASSWORD_RESET_CONFIRM_URL": "auth/password-reset-confirm?uid={uid}&token={token}", # Password reset link, using uid and token generated by Djoser password reset endpoint
    "ACTIVATION_URL": "auth/activate?uid={uid}&token={token}", # Activation link, using uid and token generated by Djoser password reset endpoint
    "EMAIL": {
        "activation": "app.email_templates.CustomActivationEmail", # To use custom HTML
        "password_reset":"app.email_templates.CustomPasswordResetEmail" # To use custom HTML
    },
    "SEND_ACTIVATION_EMAIL": True,
    "SERIALIZERS": {
        "user_create": "app.serializers.CustomUserCreateSerializer", # Serializers to use when creating users
        "user": "app.serializers.CustomUserSerializer",
    },
}


TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "app/templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "uni_hub.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
# Credentials to connect Django to the containerized DB
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'uni_hub_db',
        'USER': 'root',
        'PASSWORD': 'root',
        'HOST': 'db',
        'PORT': '3306',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Path to use when users upload using image field
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "app/media/"

# Mailhog configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "mailhog"
EMAIL_PORT = 1025
EMAIL_USE_TLS = False


# AWS S3 Storage Settings
DEFAULT_FILE_STORAGE = "storages.backends.s3boto3.S3Boto3Storage"
AWS_ACCESS_KEY_ID = "AKIA2MNVMEZIV5KHSZWM"
AWS_SECRET_ACCESS_KEY = "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"
AWS_STORAGE_BUCKET_NAME = "uni-hub-pictures"
AWS_S3_REGION_NAME = "us-east-1"


AWS_S3_CUSTOM_DOMAIN = f"{AWS_STORAGE_BUCKET_NAME}.s3.{AWS_S3_REGION_NAME}.amazonaws.com"

MEDIA_URL = f"{AWS_S3_CUSTOM_DOMAIN}/"


ZOOM_CLIENT_ID="LUm0ZZUET1OO4ritLGw7Fg"
ZOOM_CLIENT_SECRET="FvjFVTfB1piXip5pCfZw1Z4AUaKI5GvA"
ZOOM_ACCOUNT_ID="itiZJJzzSPe56mfk_AuDhA"
ZOOM_USER_EMAIL="me"